const seed = [{"title":"Haunted Mansion, The","year":1996,"genre":"Children|Comedy|Fantasy|Horror","director":"Marilyn Caile"},
{"title":"3 Bad Men","year":1998,"genre":"Western","director":"Rikki Gives"},
{"title":"Comfort of Strangers, The","year":2004,"genre":"Drama","director":"Nickolas Digan"},
{"title":"No Name on the Bullet","year":2008,"genre":"Western","director":"Kellie Spurgeon"},
{"title":"Room with a View, A","year":2009,"genre":"Drama|Romance","director":"Casandra Barstock"},
{"title":"Tales from the Golden Age (Amintiri din epoca de aur)","year":1996,"genre":"Comedy","director":"Clio Mardling"},
{"title":"Flu","year":2010,"genre":"Action|Drama|Sci-Fi","director":"Kale Govan"},
{"title":"Mary Poppins","year":1988,"genre":"Children|Comedy|Fantasy|Musical","director":"Chelsy Hamments"},
{"title":"American Pie 2","year":1986,"genre":"Comedy","director":"Carmel Meeus"},
{"title":"Passion Fish","year":1999,"genre":"Drama","director":"Killy Fonso"},
{"title":"Angelus","year":1994,"genre":"Comedy|Drama","director":"Steward Ugo"},
{"title":"Scarlet Empress, The","year":2000,"genre":"Drama","director":"Anett Degue"},
{"title":"Passion in the Desert","year":2008,"genre":"Adventure|Drama","director":"Egor Drohan"},
{"title":"#chicagoGirl: The Social Network Takes on a Dictator","year":2011,"genre":"Documentary","director":"Koral Christin"},
{"title":"Naughty Marietta","year":1999,"genre":"Drama|Musical","director":"Eugenius Doiley"},
{"title":"Stella: Live in Boston","year":1999,"genre":"Comedy","director":"Fenelia Shinner"},
{"title":"Illegal Tender","year":1996,"genre":"Crime|Drama|Thriller","director":"Moina Cordy"},
{"title":"Stuart Little","year":2012,"genre":"Children|Comedy|Fantasy","director":"Lanny Brelsford"},
{"title":"Corto Maltese: Ballad of the Salt Sea (Corto Maltese - La ballade de la mer salée)","year":2011,"genre":"Animation","director":"Jodee Firebrace"},
{"title":"Ararat","year":1985,"genre":"Drama|War","director":"May Bastable"},
{"title":"Price of Glory","year":2000,"genre":"Drama","director":"Thadeus Skeen"},
{"title":"Goyokin","year":1987,"genre":"Action|Drama","director":"Nissie Penylton"},
{"title":"Friends with Money","year":1994,"genre":"Comedy|Drama|Romance","director":"Celestyn Yaakov"},
{"title":"Joy Ride 2: Dead Ahead","year":1991,"genre":"Action|Horror|Thriller","director":"Waylan Pearl"},
{"title":"Misérables, Les","year":2009,"genre":"Drama","director":"Jaclyn Scarasbrick"},
{"title":"Poetry (Shi)","year":1994,"genre":"Drama","director":"Lonnie D'Alesco"},
{"title":"Going Overboard","year":2006,"genre":"Comedy","director":"Drona De Paoli"},
{"title":"Police Academy 3: Back in Training","year":1967,"genre":"Comedy|Crime","director":"Norris Troman"},
{"title":"Ride the Divide","year":1994,"genre":"Adventure|Documentary","director":"Mab Gonin"},
{"title":"Alone in the Dark II","year":1998,"genre":"Action|Horror","director":"Anton Trebilcock"},
{"title":"Bride Wore Black, The (La mariée était en noir)","year":1993,"genre":"Crime|Drama","director":"Nikolos Keemar"},
{"title":"Love Is Colder Than Death (Liebe ist kälter als der Tod)","year":2005,"genre":"Comedy|Crime|Romance","director":"Aland Lange"},
{"title":"Scott Pilgrim vs. the World","year":2011,"genre":"Action|Comedy|Fantasy|Musical|Romance","director":"Valencia Flageul"},
{"title":"Cameraman's Revenge, The (Mest kinematograficheskogo operatora)","year":1995,"genre":"Animation|Comedy","director":"Claude Gehring"},
{"title":"Chasing Beauty","year":2010,"genre":"Documentary","director":"Joanne Aizikowitz"},
{"title":"Ever After: A Cinderella Story","year":2012,"genre":"Comedy|Drama|Romance","director":"Kaylee Naptine"},
{"title":"Invitation, The (Zaproszenie)","year":2001,"genre":"Drama","director":"Frederico Englefield"},
{"title":"Goodbye to All That","year":2009,"genre":"Comedy|Drama","director":"Pete Phittiplace"},
{"title":"Easy Money","year":1989,"genre":"Comedy","director":"Tami Carnduff"},
{"title":"Fast and the Furious, The","year":1995,"genre":"Crime|Mystery","director":"Nerta Breese"},
{"title":"RoboCop","year":2010,"genre":"Action|Crime|Drama|Sci-Fi|Thriller","director":"Brok Beckerleg"},
{"title":"By the Light of the Silvery Moon","year":2006,"genre":"Children|Musical|Romance","director":"Boone Jobling"},
{"title":"Seven Year Itch, The","year":2004,"genre":"Comedy","director":"Dukie Paraman"},
{"title":"A Gun for Jennifer","year":1999,"genre":"Crime|Drama|Thriller","director":"Quentin Payze"},
{"title":"Lust, Caution (Se, jie)","year":2007,"genre":"Drama|Romance|Thriller|War","director":"Llewellyn Wall"},
{"title":"Anything Goes","year":2002,"genre":"Musical","director":"Barbaraanne Haslock"},
{"title":"From Beijing with Love","year":1997,"genre":"Action|Comedy","director":"Ronnie Bracco"},
{"title":"Extraordinary Adventures of Adèle Blanc-Sec, The","year":2003,"genre":"Action|Adventure|Fantasy|Mystery","director":"Hobey Clynmans"},
{"title":"Casual Relations","year":1985,"genre":"Drama","director":"Corinne Spikins"},
{"title":"Barking Dogs Never Bite (Flandersui gae)","year":2000,"genre":"Comedy|Horror","director":"Felicle Kleinhandler"}];
export default seed;